### ISSUE TITLE
Failed to send SOS message in API 26

### ISSUE THREAD

**Issue by sachuss** [sachuss/Raksha-SOS-Alert-#60]
Need to look in to the issue.

**Comment by nikhilgeo** [comment]
There is some problem with permission in API 26. 

`java.lang.SecurityException: Neither user 10085 nor current process has android.permission.READ_PHONE_STATE.`

**Comment by nikhilgeo** [comment]
https://stackoverflow.com/questions/43963177/why-is-smsmanager-requiring-read-phone-state-permission-on-some-devices-but-not

> I was looking into the Android source code and found this: android.googlesource.com/platform/frameworks/opt/telephony/+/… (method: sendTextMessage, line 263) There is a call to getSubscriptionId(), which is protected with READ_PHONE_STATE_PERMISSION, then if the app does not have this permission checked/granted, calling this method will cause the SecurityException and the app will crash. Workaround is (when app declared usage of READ_PHONE_STATE) is to grant the permission manually from the settings

**Comment by sachuss** [comment]
Rectified.
